@echo off
REM ###########################################################################
REM Script generated by Fortify Scan Wizard (c) 2011-2023 Micro Focus or one of its affiliates
REM Created on 2023/03/30 15:37:42
REM ###########################################################################
REM Generated for the following languages:
REM 	Java
REM ###########################################################################
REM FPR - the name of analysis results file
REM DEBUG - if set to true, runs SCA in debug mode
REM SOURCEANALYZER - the name of the SCA executable
REM BUILDID - the SCA build ID
REM ARGFILE - the name of the argument file that's passed to SCA
REM BYTECODE_ARGFILE - the name of the argument file for Java bytecode translation in the SCA
REM MEMORY - the memory settings for SCA
REM SCANSWITCHES - parameters to pass in the SCA analysis phase
REM LAUNCHERSWITCHES - the launcher settings that are used to invoke SCA
REM OLDFILENUMBER - this defines the file that contains the number of files within the project, it is automatically generated
REM FILENOMAXDIFF - this is the percentage of difference between the number of files which will trigger a warning by the script
REM ###########################################################################

set DEBUG=false
set SOURCEANALYZER=sourceanalyzer
set FPR="Fortifywebgoat.fpr"
set BUILDID="webgoat"
set ARGFILE="Fortifywebgoat.bat.args"
set BYTECODE_ARGFILE="Fortifywebgoat.bat.bytecode.args"
set MEMORY=-Xmx14744M -Xms400M -Xss24M 
set LAUNCHERSWITCHES=""
set SCANSWITCHES=""
set OLDFILENUMBER="Fortifywebgoat.bat.fileno"
set FILENOMAXDIFF=10
set ENABLE_BYTECODE=false

set PROJECTROOT0="D:\desktop\webgoat\webgoat1\JavaSource\org\owasp\webgoat"
IF NOT EXIST %PROJECTROOT0% (
   ECHO  ERROR: This script is being run on a different machine than it was
   ECHO         generated on or the targeted project has been moved. This script is 
   ECHO         configured to locate files at
   ECHO            %PROJECTROOT0%
   ECHO         Please modify the %%PROJECTROOT0%% variable found
   ECHO         at the top of this script to point to the corresponding directory
   ECHO         located on this machine.
   GOTO :FINISHED
)

IF %DEBUG%==true set LAUNCHERSWITCHES=-debug %LAUNCHERSWITCHES%
echo Extracting Arguments File


echo. >%ARGFILE%
echo. >%BYTECODE_ARGFILE%
SETLOCAL ENABLEDELAYEDEXPANSION
IF EXIST %0 (
   set SCAScriptFile=%0
) ELSE (
  set SCAScriptFile=%0.bat
)

set PROJECTROOT0=%PROJECTROOT0:)=^)%
FOR /f "delims=" %%a IN ('findstr /B /C:"REM ARGS" %SCAScriptFile%' ) DO (
   set argVal=%%a
   set argVal=!argVal:PROJECTROOT0_MARKER=%PROJECTROOT0:~1,-1%!
   echo !argVal:~9! >> %ARGFILE%
)
set PROJECTROOT0=%PROJECTROOT0:)=^)%
FOR /f "delims=" %%a IN ('findstr /B /C:"REM BYTECODE_ARGS" %SCAScriptFile%' ) DO (
   set ENABLE_BYTECODE=true
   set argVal=%%a
   set argVal=!argVal:PROJECTROOT0_MARKER=%PROJECTROOT0:~1,-1%!
   echo !argVal:~18! >> %BYTECODE_ARGFILE%
)
ENDLOCAL && set ENABLE_BYTECODE=%ENABLE_BYTECODE%

REM ###########################################################################
echo Cleaning previous scan artifacts
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% -clean 
IF %ERRORLEVEL% NEQ 0  (
echo sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Translating files
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% @%ARGFILE%
IF %ERRORLEVEL% NEQ 0  (
echo sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
IF %ENABLE_BYTECODE%==true (
echo Translating Java bytecode files
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% @%BYTECODE_ARGFILE%
IF %ERRORLEVEL% NEQ 0  (
echo sourceanalyzer failed, exiting
GOTO :FINISHED
)
)
REM ###########################################################################
echo Testing Difference between Translations
SETLOCAL
FOR /F "delims=" %%A in ('%SOURCEANALYZER% -b %BUILDID% -show-files ^| findstr /R /N "^" ^| find /C ":" ') DO SET FILENUMBER=%%A
IF NOT EXIST %OLDFILENUMBER% (
	ECHO It appears to be the first time running this script, setting %OLDFILENUMBER% to %FILENUMBER%
	ECHO %FILENUMBER% > %OLDFILENUMBER%
	GOTO TESTENDED
)

FOR /F "delims=" %%i IN (%OLDFILENUMBER%) DO SET OLDFILENO=%%i
set /a DIFF=%OLDFILENO% * %FILENOMAXDIFF%
set /a DIFF /=  100
set /a MAX=%OLDFILENO% + %DIFF%
set /a MIN=%OLDFILENO% - %DIFF%

IF %FILENUMBER% LSS %MIN% set SHOWWARNING=true
IF %FILENUMBER% GTR %MAX% set SHOWWARNING=true

IF DEFINED SHOWWARNING (
	ECHO WARNING: The number of files has changed by over %FILENOMAXDIFF%%%, it is recommended 
	ECHO          that this script is regenerated with the ScanWizard
)
:TESTENDED
ENDLOCAL

REM ###########################################################################
echo Starting scan
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% %SCANSWITCHES% -scan -f %FPR%
IF %ERRORLEVEL% NEQ 0  (
echo sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Finished
:FINISHED
REM ARGS "-cp"
REM ARGS "-source"
REM ARGS "1.8"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\util\Exec.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\util\ExecResults.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\util\ExecutionException.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\util\HtmlEncoder.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\util\Interceptor.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\util\ThreadWatcher.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\Authorization.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\Course.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\CreateDB.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\DatabaseUtilities.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\ECSFactory.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\Employee.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\EmployeeStub.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\ErrorScreen.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\LessonSession.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\LessonTracker.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\Parameter.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\ParameterNotFoundException.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\ParameterParser.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\Screen.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\UnauthenticatedException.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\UnauthorizedException.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\UserTracker.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\ValidationException.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\WebgoatProperties.java"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\session\WebSession.java"
REM ARGS "PROJECTROOT0_MARKER"
